name: CI Workflow

on:
  push:
    branches:
      - main
      - dev

env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build:
    strategy:
      matrix:
        dotnet-version: ["8.0.x", "6.0.x"]
        os: ["ubuntu-latest", "window-latest"]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
        name: Checkout
        with:
          fetch-depth: 0

      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          cache: true
          cache-dependency-path: "**/packages.lock.json"

      - name: Display dotnet version
        run: dotnet --version

      - name: Restore dependencies
        run: dotnet restore --no-cache --disable-parallel --verbosity minimal
